query GetBalance(
  $startDate: timestamptz
  $endDate: timestamptz
  $accountId: uuid
  $groupBy: String
) {
  balances: func_transactions_by_account_grouped_cumulative(
    args: {
      v_account_id: $accountId
      v_group_by: $groupBy
      v_start_date: $startDate
    }
    where: { date: { _gte: $startDate, _lte: $endDate } }
    order_by: { date: asc }
  ) {
    date
    sum
  }
}
