query GetCategories(
  $startDate: timestamptz
  $endDate: timestamptz
  $accountId: uuid
  $categoryType: String
  $groupByParent: Boolean
) {
  categories: func_category_by_date_type(
    args: {
      v_account_id: $accountId
      v_category_type: $categoryType
      v_end_date: $endDate
      v_start_date: $startDate
      v_parent: $groupByParent
    }
  ) {
    id
    name
    sum
  }
  amount: func_category_by_date_type_aggregate(
    args: {
      v_account_id: $accountId
      v_category_type: $categoryType
      v_end_date: $endDate
      v_start_date: $startDate
      v_parent: $groupByParent
    }
  ) {
    aggregate {
      sum {
        sum
      }
    }
  }
}
